name: 'Setup Node.js and pnpm'
description: 'Setup Node.js and pnpm for the project'

inputs:
  build-command:
    description: 'Command to build the project'
    required: false
    default: 'pnpm build'
  node-version:
    description: 'Node.js version'
    required: false
    default: '22.22.0'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: '10.22.0'

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
      shell: bash

    - name: Rebuild sqlite3
      run: |
        cd node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3
        npm run install
      shell: bash

    - name: Build
      run: ${{ inputs.build-command }}
      shell: bash
